In [1]:
import pandas as pd
import numpy as np

In [3]:
iris=pd.read_csv("https://raw.githubusercontent.com/YBI-Foundation/Dataset/main/IRIS.csv")

In [4]:
iris.head()

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [5]:
iris.describe()

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [6]:
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [8]:
iris.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [9]:
y=iris['species']

In [14]:
X=iris.drop(['species'],axis=1)

In [15]:
X.shape,y.shape

((150, 4), (150,))

In [18]:
y.unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [19]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,train_size=0.75,test_size=0.25,random_state=1)

In [22]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((112, 4), (38, 4), (112,), (38,))

In [23]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(X_train,y_train)

LogisticRegression()

In [26]:
y_pred=model.predict(X_test)
y_pred

array(['Iris-setosa', 'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-virginica',
       'Iris-setosa', 'Iris-setosa', 'Iris-virginica', 'Iris-versicolor',
       'Iris-setosa', 'Iris-virginica', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor',
       'Iris-virginica', 'Iris-versicolor', 'Iris-virginica',
       'Iris-virginica', 'Iris-setosa', 'Iris-versicolor', 'Iris-setosa'],
      dtype=object)

In [28]:
model.intercept_

array([  9.36598295,   1.42917889, -10.79516184])

In [29]:
model.coef_

array([[-0.43015959,  0.7955082 , -2.30761197, -0.95782157],
       [ 0.62761706, -0.41926978, -0.20441607, -0.77848654],
       [-0.19745747, -0.37623843,  2.51202804,  1.73630812]])

In [34]:
data=pd.DataFrame({"Actual":y_test,"Predicted":y_pred})
data

Actual        Predicted
14       Iris-setosa      Iris-setosa
98   Iris-versicolor  Iris-versicolor
75   Iris-versicolor  Iris-versicolor
16       Iris-setosa      Iris-setosa
131   Iris-virginica   Iris-virginica
56   Iris-versicolor  Iris-versicolor
141   Iris-virginica   Iris-virginica
44       Iris-setosa      Iris-setosa
29       Iris-setosa      Iris-setosa
120   Iris-virginica   Iris-virginica
94   Iris-versicolor  Iris-versicolor
5        Iris-setosa      Iris-setosa
102   Iris-virginica   Iris-virginica
51   Iris-versicolor  Iris-versicolor
78   Iris-versicolor  Iris-versicolor
42       Iris-setosa      Iris-setosa
92   Iris-versicolor  Iris-versicolor
66   Iris-versicolor  Iris-versicolor
31       Iris-setosa      Iris-setosa
35       Iris-setosa      Iris-setosa
90   Iris-versicolor  Iris-versicolor
84   Iris-versicolor  Iris-versicolor
77   Iris-versicolor   Iris-virginica
40       Iris-setosa      Iris-setosa
125   Iris-virginica   Iris-virginica
99   Iris-versicolor  Iris-versicolor
33       Iris-setosa      Iris-setosa
19       Iris-setosa      Iris-setosa
73   Iris-versicolor  Iris-versicolor
146   Iris-virginica   Iris-virginica
91   Iris-versicolor  Iris-versicolor
135   Iris-virginica   Iris-virginica
69   Iris-versicolor  Iris-versicolor
128   Iris-virginica   Iris-virginica
114   Iris-virginica   Iris-virginica
48       Iris-setosa      Iris-setosa
53   Iris-versicolor  Iris-versicolor
28       Iris-setosa      Iris-setosa

In [36]:
print("Training Score:",model.score(X_train,y_train))
print("Testing Score: ",model.score(X_test,y_test))

Training Score: 0.9821428571428571
Testing Score:  0.9736842105263158


In [37]:
from sklearn.metrics import accuracy_score
print("Accuracy Score: ",accuracy_score(y_test,y_pred))

Accuracy Score:  0.9736842105263158


In [43]:
from sklearn.metrics import confusion_matrix,classification_report,mean_absolute_error,mean_squared_error
confusion_matrix(y_test,y_pred)

array([[13,  0,  0],
       [ 0, 15,  1],
       [ 0,  0,  9]], dtype=int64)

In [39]:
print(classification_report(y_test,y_pred))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        13
Iris-versicolor       1.00      0.94      0.97        16
 Iris-virginica       0.90      1.00      0.95         9

       accuracy                           0.97        38
      macro avg       0.97      0.98      0.97        38
   weighted avg       0.98      0.97      0.97        38

